### ISSUE TITLE
Shooting bug

### ISSUE THREAD

**Issue by vineetprash** [vineetprash/HTML-Shooter#3]
User is able to shoot bullets even after end screen is displayed. They spawn and stay static.

**Comment by Shabbir-Building** [comment]
Hi Vineet,

I am interested on fix this bug. Please assign this issue to me.

Best,
Shabbir

**Comment by Shabbir-Building** [comment]
You can also assign issue #1 and #2 to me.

**Comment by vineetprash** [comment]
Regarding issues #1 and #2, I believe you need to post a comment there for me to able to assign you.
